#!/usr/bin/env bash

killall --wait --user $USER sxhkd picom polybar /usr/lib/xfce-polkit/xfce-polkit

sxhkd &
picom &
polybar main &
/usr/lib/xfce-polkit/xfce-polkit &

setxkbmap -layout eu
xset r rate 250 45
feh --bg-fill ~/.config/wallpaper.jpg
pamixer --set-volume 20

bspc monitor -d WEB TERM CODE CHAT MISC

bspc config border_width 2
bspc config window_gap 12
bspc config normal_border_color "#1a1b26"
bspc config focused_border_color "#7aa2f7"
bspc config borderless_monocle true
bspc config single_monocle true
bspc config gapless_monocle true

bspc rule -a firefox desktop=^1 follow=on
bspc rule -a Alacritty desktop =^2 follow=on
bspc rule -a Code desktop =^3 follow=on
bspc rule -a discord desktop =^4 follow=on
