#!/usr/bin/env bash

killall --wait --user $USER sxhkd picom polybar /usr/lib/xfce-polkit/xfce-polkit

sxhkd &
picom &
polybar main &
/usr/lib/xfce-polkit/xfce-polkit &

bspc monitor -d WEB TERM CODE MISC

bspc config border_width 2
bspc config window_gap 8
bspc config normal_border_color "#032344a"
bspc config focused_border_color "#7aa2f7"
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a firefox desktop=^1 follow=on
bspc rule -a Alacritty desktop =^2 follow=on
bspc rule -a Code desktop =^3 follow=on
