#!/usr/bin/env bash

super + Return
    alacritty

super + @space
    rofi -show drun -theme ~/.config/rofi/launcher.rasi

super + p
    rofi -combi-modi window,drun -show combi -theme ~/.config/rofi/launcher.rasi

super + ctrl + p
    rofi -show run -theme ~/.config/rofi/launcher.rasi

super + ctrl + {q, r}
    bspc {quit, wm -r}

super + q
    bspc node -c

super + {j, k}
    bspc node -f {next.local.!hidden.window, prev.local.!hidden.window}

super + {l, h}
    bspc desktop -f {next.local, prev.local}

super + s
    bspc node -s biggest.window.local

super + {f, t, w}
    bspc node -t {fullscreen, tiled, floating}

super + ctrl + {h, j, k, l}
    ~/.config/sxhkd/scripts/resize.sh {left, down, up, right} 100

super + Tab
    bspc desktop -f last

super + {1-9, 0}
    bspc desktop -f "^{1-9, 10}"

super + alt + {1-9, 0}
    bspc node -d "^{1-9, 10}"

{XF86AudioRaiseVolume, XF86AudioLowerVolume}
    pamixer --unmute {--increase, --decrease} 5

XF86AudioMute
    pamixer --toggle-mute
